/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:50151dcd-3937-47f0-a0cf-f7da4f353449",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_DuY2SmzyV",
    "aws_user_pools_web_client_id": "4sgs75k4em558ie8rmdbujmqnp",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://vgqc8t636i.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ptskc457vbd63j2tuwm2tpko3u.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-5jkix7azmfcwbdi5zvu3kzpzlq"
};


module.exports =  awsmobile;
